apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  generation: 27
  name: s2i-nodejs-custom
spec:
  params:
    - default: 'build'
      description: The location of the path to run s2i from.
      name: BUILD_OUTPUT_DIR
      type: string
    - default: '{{ tpl $.Values.backend.url $ }}'
      description: The location of the path to run s2i from.
      name: APP_BACKEND_URL
      type: string
    - default: 'true'
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
      type: string
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image
        type: image
  steps:
    - command:
        - s2i
        - build
        - .
        - 'quay.io/evanshortiss/s2i-nodejs-nginx:latest'
        - '-e'
        - 'BUILD_OUTPUT_DIR=$(params.BUILD_OUTPUT_DIR)'
        - '-e'
        - 'REACT_APP_BACKEND_URL=$(params.APP_BACKEND_URL)'
        - '--as-dockerfile'
        - /gen-source/Dockerfile.gen
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      name: generate
      resources: {}
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source
      workingDir: /workspace/source
    - command:
        - cat
        - /gen-source/Dockerfile.gen
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      name: print-dockerfile
      resources: {}
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source
      workingDir: /workspace/source
    - command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--layers'
        - '-f'
        - /gen-source/Dockerfile.gen
        - '-t'
        - $(resources.outputs.image.url)
        - .
      image: registry.redhat.io/rhel8/buildah
      name: build
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
        - mountPath: /gen-source
          name: gen-source
      workingDir: /gen-source
    - command:
        - buildah
        - push
        - '--tls-verify=$(params.TLSVERIFY)'
        - $(resources.outputs.image.url)
        - 'docker://$(resources.outputs.image.url)'
      image: registry.redhat.io/rhel8/buildah
      name: push
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - emptyDir: {}
      name: varlibcontainers
    - emptyDir: {}
      name: gen-source