apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-pipeline-init-run
  annotations:
    "helm.sh/hook": "post-install"
spec:
  pipelineRef:
    name: frontend-pipeline
  resources:
    - name: frontend-git-repo
      resourceRef:
        name: frontend-git-repo
    - name: frontend-image
      resourceRef:
        name: frontend-image