apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: frontend-git-repo
spec:
  params:
    - name: url
      value: 'https://github.com/Jaland/example_frontend.git'
    - name: revision
      value: main
  type: git
