apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
spec:
  resources:
    - name: frontend-git-repo
      type: git
    - name: frontend-image
      type: image
  tasks:
    - name: s2i-nodejs-custom
      params:
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: frontend-git-repo
        outputs:
          - name: image
            resource: frontend-image
      taskRef:
        kind: Task
        name: s2i-nodejs-custom
