kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: myapp
spec:
  to:
    kind: Service
    name: myapp
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
  tls:
    termination: edge