---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
        - name: {{ .Values.appName}}
          image: >-
            {{ .Values.image }}
          ports:
            - containerPort: 8080