apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-deployment
spec:
  destination:
    namespace: myapp-dev
    server: https://kubernetes.default.svc
  project: myapp-argo-project
  source:
    helm:
      parameters:
      - name: image
        value: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
      - name: appName
        value: myapp
    path: deployment
    repoURL: https://github.com/Jaland/argo-tekton-flow.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
