apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: backend-pipeline
spec:
  tasks:
    - name: clone-app
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
      taskRef:
        kind: Task
        name: clone-git-custom
