apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.appName }}
spec:
  params:
  - name: GIT_URL
    type: string
    default: '{{ .Values.git.url }}'
  - name: GIT_REVISION
    type: string
    default: '{{ .Values.git.revision }}'
  - name: APP_NAME
    type: string
    default: {{ .Values.appName }}
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: submodules
          value: 'true'
        - name: revision
          value: $(params.GIT_REVISION)
      taskRef:
        kind: Task
        name: git-clone-custom
      workspaces:
        - name: output
          workspace: app-source
    - name: s2i-java
      params:
        - name: PATH_CONTEXT
          value: .
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.namespace }}/$(params.APP_NAME)'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: s2i-java-custom
      workspaces:
        - name: source
          workspace: app-source
    - name: update-argo-app
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.namespace }}/$(params.APP_NAME)@$(tasks.s2i-java.results.IMAGE_DIGEST) }}'
        - name: APP_NAME
          value: $( params.APP_NAME )
        - name: ARGO_NAMESPACE
          value: {{ .Values.argoNamespace }}
      runAfter:
        - s2i-java
      taskRef:
        kind: Task
        name: update-app
  workspaces:
    - name: app-source