apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.appName }}
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: '{{ .Values.git.url }}'
        - name: submodules
          value: 'true'
        - name: subdirectory
          value: {{ .Values.git.context }}
        - name: revision
          value: {{ .Values.git.revision }}
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: s2i-java
      params:
        - name: PATH_CONTEXT
          value: .
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.namespace }}/{{ .Values.appName }}'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: app-source
  workspaces:
    - name: app-source