apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: backend-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/Jaland/argo-tekton-flow.git'
        - name: submodules
          value: 'true'
        - name: subdirectory
          value: helm-deployments/backend
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: s2i-java
      params:
        - name: PATH_CONTEXT
          value: .
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/user1-dev/example'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: app-source
  workspaces:
    - name: app-source